Description: Adds Python 3.2 compat
 Fixes couples of u'' and replace them with six.u('')
Author: Thomas Goirand <zigo@debian.org>
Forwarded: no
Last-Update: 2014-06-11

--- python-keystoneclient-0.9.0.orig/keystoneclient/tests/test_utils.py
+++ python-keystoneclient-0.9.0/keystoneclient/tests/test_utils.py
@@ -34,7 +34,7 @@ class FakeManager(object):
     resources = {
         '1234': {'name': 'entity_one'},
         '8e8ec658-c7b0-4243-bdf8-6f7f2952c0d0': {'name': 'entity_two'},
-        '\xe3\x82\xbdtest': {'name': u'\u30bdtest'},
+        '\xe3\x82\xbdtest': {'name': six.u('\u30bdtest')},
         '5678': {'name': '9876'}
     }
 
@@ -114,7 +114,7 @@ class PrintTestCase(test_utils.TestCase)
         self.addCleanup(setattr, sys, 'stdout', self.old_stdout)
 
     def test_print_list_unicode(self):
-        name = u'\u540d\u5b57'
+        name = six.u('\u540d\u5b57')
         objs = [FakeObject(name)]
         # NOTE(Jeffrey4l) If the text's encode is proper, this method will not
         # raise UnicodeEncodeError exceptions
@@ -127,7 +127,7 @@ class PrintTestCase(test_utils.TestCase)
         self.assertIn(name, output)
 
     def test_print_dict_unicode(self):
-        name = u'\u540d\u5b57'
+        name = six.u('\u540d\u5b57')
         utils.print_dict({'name': name})
         output = self.stdout.getvalue()
         # In Python 2, output will be bytes, while in Python 3, it will not.
--- python-keystoneclient-0.9.0.orig/keystoneclient/tests/test_discovery.py
+++ python-keystoneclient-0.9.0/keystoneclient/tests/test_discovery.py
@@ -119,7 +119,7 @@ V3_VERSION = {'id': 'v3.0',
               'status': 'stable',
               'updated': UPDATED}
 
-V3_TOKEN = u'3e2813b7ba0b4006840c3825860b86ed',
+V3_TOKEN = six.u('3e2813b7ba0b4006840c3825860b86ed'),
 V3_AUTH_RESPONSE = jsonutils.dumps({
     "token": {
         "methods": [
